In [44]:
import pandas as pd
import numpy as np
df = pd.read_csv('C:/Users/daryn/Downloads/bookings.csv')

In [3]:
df

,Hotel,Is canceled,Lead time,Arrival full date,Arrival date year,Arrival date month,Arrival date week number,Arrival date day of month,Stays in weekend nights,Stays in week nights,...,Children,Babies,Meal,Country,Reserved room type,Customer type,Reservation status,Reservation status date,Stays total nights,Assigned room type
0,City Hotel,1,302,2015-07-01,2015,April,49,13,0,5,...,0,0,BB,ESP,E,Transient,Check-Out,2015-07-01,5,D
1,Resort Hotel,0,11,2015-07-02,2016,April,25,15,1,2,...,0,0,BB,USA,C,Group,Check-Out,2015-07-02,3,C
2,Resort Hotel,0,317,2015-07-03,2016,December,40,14,2,2,...,0,0,BB,GBR,F,Contract,Canceled,2015-07-03,4,F
3,City Hotel,1,79,2015-07-04,2016,February,24,23,2,4,...,0,0,HB,PRT,G,Transient,Canceled,2015-07-04,6,G
4,City Hotel,1,215,2015-07-05,2017,May,14,16,2,1,...,0,0,HB,ITA,D,Transient,Check-Out,2015-07-05,3,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,City Hotel,0,110,2016-11-07,2016,March,8,26,1,5,...,0,0,BB,GBR,G,Transient,Check-Out,2016-11-07,6,G
496,City Hotel,1,13,2016-11-08,2017,September,19,25,0,3,...,0,0,BB,PRT,D,Contract,Check-Out,2016-11-08,3,D
497,City Hotel,0,230,2016-11-09,2017,September,38,12,3,1,...,0,0,Undefined,GBR,G,Transient,Check-Out,2016-11-09,4,G
498,Resort Hotel,1,83,2016-11-10,2016,November,3,11,1,4,...,0,0,BB,BRA,F,Transient,Canceled,2016-11-10,5,F
499,Resort Hotel,0,129,2016-11-11,2015,October,5,5,0,3,...,0,0,BB,USA,E,Transient,No-Show,2016-11-11,3,E

In [4]:
df.shape

(500, 21)

In [5]:
df.dtypes

Hotel                          str
Is canceled                  int64
Lead time                    int64
Arrival full date              str
Arrival date year            int64
Arrival date month             str
Arrival date week number     int64
Arrival date day of month    int64
Stays in weekend nights      int64
Stays in week nights         int64
Adults                       int64
Children                     int64
Babies                       int64
Meal                           str
Country                        str
Reserved room type             str
Customer type                  str
Reservation status             str
Reservation status date        str
Stays total nights           int64
Assigned room type             str
dtype: object

In [6]:
df.head(7)

,Hotel,Is canceled,Lead time,Arrival full date,Arrival date year,Arrival date month,Arrival date week number,Arrival date day of month,Stays in weekend nights,Stays in week nights,...,Children,Babies,Meal,Country,Reserved room type,Customer type,Reservation status,Reservation status date,Stays total nights,Assigned room type
0,City Hotel,1,302,2015-07-01,2015,April,49,13,0,5,...,0,0,BB,ESP,E,Transient,Check-Out,2015-07-01,5,D
1,Resort Hotel,0,11,2015-07-02,2016,April,25,15,1,2,...,0,0,BB,USA,C,Group,Check-Out,2015-07-02,3,C
2,Resort Hotel,0,317,2015-07-03,2016,December,40,14,2,2,...,0,0,BB,GBR,F,Contract,Canceled,2015-07-03,4,F
3,City Hotel,1,79,2015-07-04,2016,February,24,23,2,4,...,0,0,HB,PRT,G,Transient,Canceled,2015-07-04,6,G
4,City Hotel,1,215,2015-07-05,2017,May,14,16,2,1,...,0,0,HB,ITA,D,Transient,Check-Out,2015-07-05,3,D
5,City Hotel,0,338,2015-07-06,2015,March,26,18,1,1,...,0,0,HB,ESP,G,Transient-Party,Check-Out,2015-07-06,2,G
6,City Hotel,1,263,2015-07-07,2016,January,38,22,1,3,...,0,0,Undefined,PRT,B,Transient,Canceled,2015-07-07,4,B

In [21]:
bookings = df.rename(columns={'Hotel': 'hotel',
                   'Is canceled': 'is_canceled',
                   'Lead time': 'lead_time',
                   'Arrival full date': 'arrival_full_date',
                   'Arrival date year': 'arrival_date_year',
                   'Arrival date month': 'arrival_date_month',
                   'Arrival date week number': 'arrival_date_week_number',
                   'Arrival date day of month': 'arrival_date_day_of_month',
                   'Stays in weekend nights': 'stays_in_weekend_nights',
                   'Stays in week nights': 'stays_in_week_nights',
                   'Adults': 'adults',
                   'Children': 'children',
                   'Babies': 'babies',
                   'Meal': 'meal',
                   'Country': 'country',
                   'Reserved room type': 'reserved_room_type',
                   'Customer type': 'customer_type',
                   'Reservation status': 'reservation_status',
                   'Reservation status date': 'reservation_status_date',
                   'Stays total nights': 'stays_total_nights',
                   'Assigned room type': 'assigned_room_type'
                  })

In [20]:
print(df.columns)

Index(['Hotel', 'Is canceled', 'Lead time', 'Arrival full date',
       'Arrival date year', 'Arrival date month', 'Arrival date week number',
       'Arrival date day of month', 'Stays in weekend nights',
       'Stays in week nights', 'Adults', 'Children', 'Babies', 'Meal',
       'Country', 'Reserved room type', 'Customer type', 'Reservation status',
       'Reservation status date', 'Stays total nights', 'Assigned room type'],
      dtype='str')

In [22]:
bookings

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,children,babies,meal,country,reserved_room_type,customer_type,reservation_status,reservation_status_date,stays_total_nights,assigned_room_type
0,City Hotel,1,302,2015-07-01,2015,April,49,13,0,5,...,0,0,BB,ESP,E,Transient,Check-Out,2015-07-01,5,D
1,Resort Hotel,0,11,2015-07-02,2016,April,25,15,1,2,...,0,0,BB,USA,C,Group,Check-Out,2015-07-02,3,C
2,Resort Hotel,0,317,2015-07-03,2016,December,40,14,2,2,...,0,0,BB,GBR,F,Contract,Canceled,2015-07-03,4,F
3,City Hotel,1,79,2015-07-04,2016,February,24,23,2,4,...,0,0,HB,PRT,G,Transient,Canceled,2015-07-04,6,G
4,City Hotel,1,215,2015-07-05,2017,May,14,16,2,1,...,0,0,HB,ITA,D,Transient,Check-Out,2015-07-05,3,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,City Hotel,0,110,2016-11-07,2016,March,8,26,1,5,...,0,0,BB,GBR,G,Transient,Check-Out,2016-11-07,6,G
496,City Hotel,1,13,2016-11-08,2017,September,19,25,0,3,...,0,0,BB,PRT,D,Contract,Check-Out,2016-11-08,3,D
497,City Hotel,0,230,2016-11-09,2017,September,38,12,3,1,...,0,0,Undefined,GBR,G,Transient,Check-Out,2016-11-09,4,G
498,Resort Hotel,1,83,2016-11-10,2016,November,3,11,1,4,...,0,0,BB,BRA,F,Transient,Canceled,2016-11-10,5,F
499,Resort Hotel,0,129,2016-11-11,2015,October,5,5,0,3,...,0,0,BB,USA,E,Transient,No-Show,2016-11-11,3,E

In [23]:
print(bookings.columns)

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_full_date',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'reserved_room_type', 'customer_type', 'reservation_status',
       'reservation_status_date', 'stays_total_nights', 'assigned_room_type'],
      dtype='str')

In [38]:
top_countries = (
    bookings[bookings['is_canceled'] == 0]
    .groupby('country')
    ['hotel']
    .count()
    .sort_values(ascending=False)
    .head(5)
)

print(top_countries)

country
PRT    138
GBR     57
ESP     31
FRA     25
DEU     22
Name: hotel, dtype: int64

In [43]:
total_nights = bookings.groupby('hotel')['stays_total_nights'].mean()
print(total_nights)

hotel
City Hotel      4.406143
Resort Hotel    4.536232
Name: stays_total_nights, dtype: float64

In [41]:
total_nights

np.float64(62.5)

In [47]:
overbooked_count = (bookings['reserved_room_type'] != bookings['assigned_room_type']).sum()
overbooked_count

np.int64(76)

In [67]:
success_book2016 = (
    bookings
    .query("`is_canceled` == 0 and `arrival_date_year` == 2016")
    ['arrival_date_month']
    .value_counts()
)
success_book2016

arrival_date_month
October      23
December     17
January      17
July         17
September    17
April        16
February     15
June         14
May          14
August       12
March        11
November      9
Name: count, dtype: int64

In [68]:
success_book2017 = (
    bookings
    .query("`is_canceled` == 0 and `arrival_date_year` == 2017")
    ['arrival_date_month']
    .value_counts()
)
print(success_book2017)

arrival_date_month
November     11
April        10
December     10
June          8
July          8
September     8
February      7
January       6
October       6
May           5
March         5
August        4
Name: count, dtype: int64

In [116]:
canceled_city = (
    bookings
    .query("`is_canceled` == 1 and `hotel` == 'City Hotel'")
    .groupby('arrival_date_year')['arrival_date_month']
    .value_counts()
)

print(canceled_city)

arrival_date_year  arrival_date_month
2015               March                 4
                   June                  3
                   December              2
                   August                2
                   April                 1
                   May                   1
                   January               1
                   July                  1
                   September             1
                   February              1
                   October               1
2016               January               8
                   November              7
                   May                   7
                   August                6
                   July                  5
                   September             5
                   December              4
                   October               4
                   April                 2
                   February              2
                   March                 2
                   June                  2
2017               January               5
                   May                   4
                   October               3
                   February              3
                   September             3
                   March                 2
                   July                  2
                   August                1
                   December              1
                   June                  1
Name: count, dtype: int64

In [78]:
print(bookings['hotel'].unique())
print(bookings['is_canceled'].unique())

<StringArray>
['City Hotel', 'Resort Hotel']
Length: 2, dtype: str
[1 0]

In [86]:
print(bookings['adults'].mean())
print(bookings['children'].mean())
print(bookings['babies'].mean())

1.92
0.238
0.014

In [91]:
bookings['total_kids'] = bookings['children'] + bookings['babies']

In [95]:
bookings['total_kids']

0      0
1      0
2      0
3      0
4      0
      ..
495    0
496    0
497    0
498    0
499    0
Name: total_kids, Length: 500, dtype: int64

In [96]:
bookings['total_kids'].sum()

np.int64(126)

In [112]:
bookings['has_kids'] = bookings['total_kids'] > 0

In [113]:
bookings['has_kids'].sum()

np.int64(101)

In [114]:
bookings.groupby('has_kids')['is_canceled'].mean() * 100

has_kids
False    30.075188
True     35.643564
Name: is_canceled, dtype: float64